using System;
using QuestPDF;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace ZhangDan.App.Reporting;

/// <summary>把组合好的报表内容写成 .pdf(QuestPDF Community;中文用系统字体 Microsoft YaHei)。</summary>
internal static class ReportPdf
{
    private static bool _licensed;

    /// <summary>设置 Community 许可(免费门槛内;含水印即 Community 标识,勿去)。</summary>
    public static void EnsureLicense()
    {
        if (_licensed)
            return;
        QuestPDF.Settings.License = LicenseType.Community;
        _licensed = true;
    }

    public static void Generate(string path, string title, ReportContent content)
    {
        EnsureLicense();
        Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(34);
                page.DefaultTextStyle(t => t.FontSize(10).FontFamily("Microsoft YaHei"));
                page.Header().Text(title).FontSize(16).SemiBold();
                page.Content().PaddingTop(6).Column(col =>
                {
                    foreach (var sheet in content.Sheets)
                    {
                        WriteSheet(col, sheet);
                        if (sheet.Title == "支出分类占比" && content.SharePng is not null)
                            col.Item().Image(content.SharePng);
                        if (sheet.Title == "跨周期趋势" && content.TrendPng is not null)
                            col.Item().Image(content.TrendPng);
                    }
                });
                page.Footer().AlignCenter().Text("Generated by 账单管理 · QuestPDF Community");
            });
        }).GeneratePdf(path);
    }

    private static void WriteSheet(ColumnDescriptor col, ReportSheet sheet)
    {
        col.Item().PaddingTop(8).Text(sheet.Title).FontSize(13).SemiBold();
        col.Item().Table(table =>
        {
            table.ColumnsDefinition(cd =>
            {
                int cols = Math.Max(1, sheet.Headers.Count);
                for (int i = 0; i < cols; i++)
                    cd.RelativeColumn();
            });
            if (sheet.Headers.Count > 0)
            {
                table.Header(header =>
                {
                    foreach (var h in sheet.Headers)
                        header.Cell().Element(el => el.Text(h).SemiBold());
                });
            }
            foreach (var row in sheet.Rows)
            {
                foreach (var v in row)
                    table.Cell().Element(el => el.Text(v ?? ""));
            }
        });
    }
}
