using System;
using System.Linq;
using QuestPDF;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace ZhangDan.App.Reporting;

/// <summary>把组合好的报表内容写成 .pdf(QuestPDF Community;中文用系统字体 Microsoft YaHei)。</summary>
internal static class ReportPdf
{
    private static bool _licensed;

    /// <summary>设置 Community 许可(免费门槛内;含水印即 Community 标识,勿去)。</summary>
    public static void EnsureLicense()
    {
        if (_licensed)
            return;
        QuestPDF.Settings.License = LicenseType.Community;
        _licensed = true;
    }

    public static void Generate(string path, string title, ReportContent content)
    {
        EnsureLicense();
        Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(34);
                page.DefaultTextStyle(t => t.FontSize(10).FontFamily("Microsoft YaHei"));
                page.Header().Text(title).FontSize(16).SemiBold();
                page.Content().PaddingTop(6).Column(col =>
                {
                    foreach (var sheet in content.Sheets)
                    {
                        WriteSheet(col, sheet);
                        if (sheet.Title == "支出分类占比" && content.SharePng is not null)
                            col.Item().Image(content.SharePng);
                        if (sheet.Title == "跨周期趋势")
                        {
                            if (content.TrendPng is not null)
                            {
                                col.Item().Image(content.TrendPng);
                                WriteTrendCaption(col, content);
                            }
                            else
                            {
                                col.Item().Text("(趋势图渲染失败,已跳过)");
                            }
                        }
                    }
                });
                page.Footer().AlignCenter().Text("Generated by 账单管理 · QuestPDF Community");
            });
        }).GeneratePdf(path);
    }

    private static void WriteSheet(ColumnDescriptor col, ReportSheet sheet)
    {
        col.Item().PaddingTop(8).Text(sheet.Title).FontSize(13).SemiBold();
        col.Item().Table(table =>
        {
            table.ColumnsDefinition(cd =>
            {
                int cols = Math.Max(1, sheet.Headers.Count);
                for (int i = 0; i < cols; i++)
                    cd.RelativeColumn();
            });
            if (sheet.Headers.Count > 0)
            {
                table.Header(header =>
                {
                    foreach (var h in sheet.Headers)
                        header.Cell().Element(el => el.Text(h).SemiBold());
                });
            }
            foreach (var row in sheet.Rows)
            {
                foreach (var v in row)
                    table.Cell().Element(el => el.Text(v ?? ""));
            }
        });
    }

    /// <summary>趋势图说明 + 图例:横轴=周期映射、色块=分类(QuestPDF 中文渲染,避免图内中文方块)。</summary>
    private static void WriteTrendCaption(ColumnDescriptor col, ReportContent content)
    {
        col.Item().PaddingTop(4).Text("趋势图说明:横轴 = 周期(按时间序)").FontSize(9);
        var map = string.Join("、", content.TrendPeriodMap.Select((n, i) => $"P{i} = {n}"));
        col.Item().Text(map).FontSize(9);
        col.Item().PaddingTop(2).Text("说明:淡色带/顶部折线 = 支出分类(顶线读总量、折线读该分类趋势);纵轴为金额(元)或占比 %,按生成时选择。")
            .FontSize(9);
        if (content.TrendCats.Count > 0)
        {
            col.Item().PaddingTop(2).Text("图例:").FontSize(9).SemiBold();
            col.Item().Table(table =>
            {
                table.ColumnsDefinition(cd =>
                {
                    cd.ConstantColumn(20);
                    cd.RelativeColumn();
                });
                foreach (var cat in content.TrendCats)
                {
                    table.Cell().Element(e => e.Width(20).Height(10).Background(SafeColor(cat.Hex)));
                    table.Cell().Element(el => el.Text(cat.Name).FontSize(9));
                }
            });
        }
    }

    private static string SafeColor(string hex)
    {
        try
        {
            return Color.FromHex(hex);
        }
        catch
        {
            return "#B0BEC5";
        }
    }
}
